/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import java.awt.CardLayout;
import java.awt.Color;

/**
 *
 * @author Jalloh
 */
public class GestionReservationsEmprunts extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GestionReservationsEmprunts() {
        initComponents();
//        mainPanel.add(new pannel1());
//        mainPanel.add(new pannel2());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        EmpruntPanel = new javax.swing.JPanel();
        panEmpCours = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEmpCours = new javax.swing.JTable();
        menuEmpPanel = new javax.swing.JPanel();
        rendreButton = new javax.swing.JButton();
        emprunterButton = new javax.swing.JButton();
        affEmpButton = new javax.swing.JButton();
        affExempButton = new javax.swing.JButton();
        panExemplaires = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableExemplaires = new javax.swing.JTable();
        ReservationPanel = new javax.swing.JPanel();
        panResaCours = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableResaCours = new javax.swing.JTable();
        menuResaPanel = new javax.swing.JPanel();
        annulerResaButton = new javax.swing.JButton();
        reserverButton = new javax.swing.JButton();
        affResaButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        empruntsButton = new javax.swing.JButton();
        ReservationButton = new javax.swing.JButton();
        retourButton = new javax.swing.JButton();
        titleResaEmpLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        typeOeuvreLabel1 = new javax.swing.JLabel();
        identifiantLabel1 = new javax.swing.JLabel();
        auteurLabel1 = new javax.swing.JLabel();
        titreLabel1 = new javax.swing.JLabel();
        categorieLabel1 = new javax.swing.JLabel();
        nbExemplaire1 = new javax.swing.JLabel();
        identifiantLabelValue6 = new javax.swing.JLabel();
        identifiantLabelValue7 = new javax.swing.JLabel();
        identifiantLabelValue8 = new javax.swing.JLabel();
        identifiantLabelValue9 = new javax.swing.JLabel();
        identifiantLabelValue10 = new javax.swing.JLabel();
        identifiantLabelValue11 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        EmpruntPanel.setBackground(new java.awt.Color(255, 255, 255));

        panEmpCours.setBackground(new java.awt.Color(255, 255, 255));
        panEmpCours.setBorder(javax.swing.BorderFactory.createTitledBorder("Emprunts en cours"));

        jScrollPane1.getViewport().setBackground(Color.white);
        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tableEmpCours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Exemplaire", "Usager", "Date emprunt", "Date Retour"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEmpCours.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableEmpCours);

        javax.swing.GroupLayout panEmpCoursLayout = new javax.swing.GroupLayout(panEmpCours);
        panEmpCours.setLayout(panEmpCoursLayout);
        panEmpCoursLayout.setHorizontalGroup(
            panEmpCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEmpCoursLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
        );
        panEmpCoursLayout.setVerticalGroup(
            panEmpCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        menuEmpPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuEmpPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        rendreButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rendreButton.setText("Rendre");
        rendreButton.setEnabled(false);
        rendreButton.setPreferredSize(new java.awt.Dimension(95, 31));

        emprunterButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        emprunterButton.setText("Emprunter");
        emprunterButton.setEnabled(false);
        emprunterButton.setPreferredSize(new java.awt.Dimension(95, 31));

        affEmpButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        affEmpButton.setText("Afficher emprunts");
        affEmpButton.setPreferredSize(new java.awt.Dimension(95, 31));

        affExempButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        affExempButton.setText("Afficher exemplaires");
        affExempButton.setPreferredSize(new java.awt.Dimension(95, 31));

        javax.swing.GroupLayout menuEmpPanelLayout = new javax.swing.GroupLayout(menuEmpPanel);
        menuEmpPanel.setLayout(menuEmpPanelLayout);
        menuEmpPanelLayout.setHorizontalGroup(
            menuEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEmpPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(menuEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(affEmpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emprunterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rendreButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(affExempButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        menuEmpPanelLayout.setVerticalGroup(
            menuEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuEmpPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rendreButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emprunterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(menuEmpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(affEmpButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(affExempButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        panExemplaires.setBackground(new java.awt.Color(255, 255, 255));
        panExemplaires.setBorder(javax.swing.BorderFactory.createTitledBorder("Exemplaires"));

        jScrollPane2.getViewport().setBackground(Color.white);
        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tableExemplaires.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Etat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableExemplaires.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tableExemplaires);

        javax.swing.GroupLayout panExemplairesLayout = new javax.swing.GroupLayout(panExemplaires);
        panExemplaires.setLayout(panExemplairesLayout);
        panExemplairesLayout.setHorizontalGroup(
            panExemplairesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panExemplairesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );
        panExemplairesLayout.setVerticalGroup(
            panExemplairesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout EmpruntPanelLayout = new javax.swing.GroupLayout(EmpruntPanel);
        EmpruntPanel.setLayout(EmpruntPanelLayout);
        EmpruntPanelLayout.setHorizontalGroup(
            EmpruntPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpruntPanelLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(EmpruntPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(menuEmpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EmpruntPanelLayout.createSequentialGroup()
                        .addComponent(panEmpCours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panExemplaires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2))
        );
        EmpruntPanelLayout.setVerticalGroup(
            EmpruntPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpruntPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuEmpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(EmpruntPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panEmpCours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panExemplaires, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.add(EmpruntPanel, "panel1");

        ReservationPanel.setBackground(new java.awt.Color(255, 255, 255));

        panResaCours.setBackground(new java.awt.Color(255, 255, 255));
        panResaCours.setBorder(javax.swing.BorderFactory.createTitledBorder("Réservations en cours"));

        jScrollPane5.getViewport().setBackground(Color.white);
        jScrollPane5.setBackground(new java.awt.Color(255, 255, 255));

        tableResaCours.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Exemplaire", "Usager", "Date emprunt", "Date Retour"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableResaCours.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tableResaCours);

        javax.swing.GroupLayout panResaCoursLayout = new javax.swing.GroupLayout(panResaCours);
        panResaCours.setLayout(panResaCoursLayout);
        panResaCoursLayout.setHorizontalGroup(
            panResaCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panResaCoursLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane5))
        );
        panResaCoursLayout.setVerticalGroup(
            panResaCoursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
        );

        menuResaPanel.setBackground(new java.awt.Color(255, 255, 255));
        menuResaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        annulerResaButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        annulerResaButton.setText("Annuler");
        annulerResaButton.setEnabled(false);

        reserverButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reserverButton.setText("Réserver");
        reserverButton.setEnabled(false);
        reserverButton.setPreferredSize(new java.awt.Dimension(95, 31));

        affResaButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        affResaButton.setText("Afficher ");
        affResaButton.setPreferredSize(new java.awt.Dimension(95, 31));

        javax.swing.GroupLayout menuResaPanelLayout = new javax.swing.GroupLayout(menuResaPanel);
        menuResaPanel.setLayout(menuResaPanelLayout);
        menuResaPanelLayout.setHorizontalGroup(
            menuResaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuResaPanelLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(reserverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(affResaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(annulerResaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );
        menuResaPanelLayout.setVerticalGroup(
            menuResaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuResaPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(menuResaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulerResaButton)
                    .addComponent(reserverButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(affResaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ReservationPanelLayout = new javax.swing.GroupLayout(ReservationPanel);
        ReservationPanel.setLayout(ReservationPanelLayout);
        ReservationPanelLayout.setHorizontalGroup(
            ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
            .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ReservationPanelLayout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(menuResaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panResaCours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ReservationPanelLayout.setVerticalGroup(
            ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
            .addGroup(ReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ReservationPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(menuResaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(4, 4, 4)
                    .addComponent(panResaCours, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        mainPanel.add(ReservationPanel, "panel2");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        empruntsButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        empruntsButton.setText("Emprunts");
        empruntsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empruntsButtonActionPerformed(evt);
            }
        });

        ReservationButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ReservationButton.setText("Réservations");
        ReservationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservationButtonActionPerformed(evt);
            }
        });

        retourButton.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        retourButton.setText("Retour");
        retourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(empruntsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReservationButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(retourButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(empruntsButton)
                .addGap(90, 90, 90)
                .addComponent(ReservationButton)
                .addGap(90, 90, 90)
                .addComponent(retourButton)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        titleResaEmpLabel.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        titleResaEmpLabel.setText("Gestion des Réservations et Emprunts");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        typeOeuvreLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        typeOeuvreLabel1.setForeground(new java.awt.Color(0, 0, 255));
        typeOeuvreLabel1.setText("Type de l'oeuvre");

        identifiantLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        identifiantLabel1.setForeground(new java.awt.Color(0, 0, 255));
        identifiantLabel1.setText("Identifiant ");

        auteurLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        auteurLabel1.setForeground(new java.awt.Color(0, 0, 255));
        auteurLabel1.setText("Auteur");

        titreLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titreLabel1.setForeground(new java.awt.Color(0, 0, 255));
        titreLabel1.setText("Titre");

        categorieLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        categorieLabel1.setForeground(new java.awt.Color(0, 0, 255));
        categorieLabel1.setText("Catégorie");

        nbExemplaire1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nbExemplaire1.setForeground(new java.awt.Color(0, 0, 255));
        nbExemplaire1.setText("Nombre \nd'exemplaire");

        identifiantLabelValue6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        identifiantLabelValue6.setText("1");

        identifiantLabelValue7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        identifiantLabelValue7.setText("1");

        identifiantLabelValue8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        identifiantLabelValue8.setText("1");

        identifiantLabelValue9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        identifiantLabelValue9.setText("1");

        identifiantLabelValue10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        identifiantLabelValue10.setText("1");

        identifiantLabelValue11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        identifiantLabelValue11.setText("1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(titreLabel1)
                        .addGap(58, 58, 58)
                        .addComponent(identifiantLabelValue7))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(identifiantLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(identifiantLabelValue6))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(categorieLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(identifiantLabelValue8))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 309, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(typeOeuvreLabel1)
                    .addComponent(nbExemplaire1)
                    .addComponent(auteurLabel1))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(identifiantLabelValue10)
                    .addComponent(identifiantLabelValue11)
                    .addComponent(identifiantLabelValue9))
                .addGap(195, 195, 195))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeOeuvreLabel1)
                    .addComponent(identifiantLabel1)
                    .addComponent(identifiantLabelValue6)
                    .addComponent(identifiantLabelValue9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titreLabel1)
                    .addComponent(identifiantLabelValue7)
                    .addComponent(auteurLabel1)
                    .addComponent(identifiantLabelValue10))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(identifiantLabelValue8)
                        .addComponent(nbExemplaire1)
                        .addComponent(identifiantLabelValue11))
                    .addComponent(categorieLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(titleResaEmpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(126, 126, 126))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleResaEmpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ReservationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservationButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panel2");
    }//GEN-LAST:event_ReservationButtonActionPerformed

    private void empruntsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empruntsButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "panel1");
    }//GEN-LAST:event_empruntsButtonActionPerformed

    private void retourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourButtonActionPerformed
        Menu m = new Menu();
        this.dispose();
        m.setVisible(true);
    }//GEN-LAST:event_retourButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionReservationsEmprunts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionReservationsEmprunts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionReservationsEmprunts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionReservationsEmprunts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionReservationsEmprunts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmpruntPanel;
    private javax.swing.JButton ReservationButton;
    private javax.swing.JPanel ReservationPanel;
    private javax.swing.JButton affEmpButton;
    private javax.swing.JButton affExempButton;
    private javax.swing.JButton affResaButton;
    private javax.swing.JButton annulerResaButton;
    private javax.swing.JLabel auteurLabel1;
    private javax.swing.JLabel categorieLabel1;
    private javax.swing.JButton emprunterButton;
    private javax.swing.JButton empruntsButton;
    private javax.swing.JLabel identifiantLabel1;
    private javax.swing.JLabel identifiantLabelValue10;
    private javax.swing.JLabel identifiantLabelValue11;
    private javax.swing.JLabel identifiantLabelValue6;
    private javax.swing.JLabel identifiantLabelValue7;
    private javax.swing.JLabel identifiantLabelValue8;
    private javax.swing.JLabel identifiantLabelValue9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel menuEmpPanel;
    private javax.swing.JPanel menuResaPanel;
    private javax.swing.JLabel nbExemplaire1;
    private javax.swing.JPanel panEmpCours;
    private javax.swing.JPanel panExemplaires;
    private javax.swing.JPanel panResaCours;
    private javax.swing.JButton rendreButton;
    private javax.swing.JButton reserverButton;
    private javax.swing.JButton retourButton;
    public static javax.swing.JTable tableEmpCours;
    public static javax.swing.JTable tableExemplaires;
    public static javax.swing.JTable tableResaCours;
    private javax.swing.JLabel titleResaEmpLabel;
    private javax.swing.JLabel titreLabel1;
    private javax.swing.JLabel typeOeuvreLabel1;
    // End of variables declaration//GEN-END:variables
}
