/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IHM;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author SIMO
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GestionUsager = new javax.swing.JButton();
        GestionExamplairesOeuvres = new javax.swing.JButton();
        Deconnecter = new javax.swing.JButton();
        GestionReservationsEmprunts1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(410, 410));
        setMinimumSize(new java.awt.Dimension(410, 410));
        setPreferredSize(new java.awt.Dimension(410, 410));
        getContentPane().setLayout(null);

        GestionUsager.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GestionUsager.setText("Gestion Usager");
        GestionUsager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionUsagerActionPerformed(evt);
            }
        });
        getContentPane().add(GestionUsager);
        GestionUsager.setBounds(50, 20, 300, 68);

        GestionExamplairesOeuvres.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GestionExamplairesOeuvres.setText("Gestion Examplaires et Oeuvres");
        GestionExamplairesOeuvres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionExamplairesOeuvresActionPerformed(evt);
            }
        });
        getContentPane().add(GestionExamplairesOeuvres);
        GestionExamplairesOeuvres.setBounds(50, 110, 300, 68);

        Deconnecter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Deconnecter.setText("Deconnecter");
        Deconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnecterActionPerformed(evt);
            }
        });
        getContentPane().add(Deconnecter);
        Deconnecter.setBounds(50, 290, 300, 68);

        GestionReservationsEmprunts1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GestionReservationsEmprunts1.setText("Gestion Reservations et Emprunts");
        GestionReservationsEmprunts1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionReservationsEmprunts1ActionPerformed(evt);
            }
        });
        getContentPane().add(GestionReservationsEmprunts1);
        GestionReservationsEmprunts1.setBounds(50, 200, 300, 68);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionUsagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionUsagerActionPerformed
        // TODO add your handling code here:
        GestionUsager gu=new GestionUsager();
        this.dispose();
        gu.setVisible(true);
    }//GEN-LAST:event_GestionUsagerActionPerformed

    private void DeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnecterActionPerformed
        // TODO add your handling code here:
        Authentification a=new Authentification();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_DeconnecterActionPerformed

    private void GestionExamplairesOeuvresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionExamplairesOeuvresActionPerformed
        // TODO add your handling code here:
        GestionExamplairesOeuvres geo=new GestionExamplairesOeuvres();
        this.dispose();
        geo.setVisible(true);
    }//GEN-LAST:event_GestionExamplairesOeuvresActionPerformed

    private void GestionReservationsEmprunts1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionReservationsEmprunts1ActionPerformed
        // TODO add your handling code here:
        GestionReservationsEmprunts gre=new GestionReservationsEmprunts();
        this.dispose();
        gre.setVisible(true);
    }//GEN-LAST:event_GestionReservationsEmprunts1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deconnecter;
    private javax.swing.JButton GestionExamplairesOeuvres;
    private javax.swing.JButton GestionReservationsEmprunts1;
    private javax.swing.JButton GestionUsager;
    // End of variables declaration//GEN-END:variables
}
