package IHM;

import java.awt.Dimension;
import java.awt.Toolkit;
/**
 * 
 * @author Diallo & Janati
 */
public class Menu extends javax.swing.JFrame {

    public Menu() {

        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GestionUsager = new javax.swing.JButton();
        GestionOeuvresExamplaires = new javax.swing.JButton();
        Deconnecter = new javax.swing.JButton();
        GestionReservationsEmprunts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setMinimumSize(new java.awt.Dimension(410, 410));
        getContentPane().setLayout(null);

        GestionUsager.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GestionUsager.setText("Gestion Usager");
        GestionUsager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionUsagerActionPerformed(evt);
            }
        });
        getContentPane().add(GestionUsager);
        GestionUsager.setBounds(50, 20, 300, 68);

        GestionOeuvresExamplaires.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GestionOeuvresExamplaires.setText("Gestion Oeuvres et Examplaires");
        GestionOeuvresExamplaires.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionOeuvresExamplairesActionPerformed(evt);
            }
        });
        getContentPane().add(GestionOeuvresExamplaires);
        GestionOeuvresExamplaires.setBounds(50, 110, 300, 68);

        Deconnecter.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Deconnecter.setText("Deconnecter");
        Deconnecter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeconnecterActionPerformed(evt);
            }
        });
        getContentPane().add(Deconnecter);
        Deconnecter.setBounds(50, 290, 300, 68);

        GestionReservationsEmprunts.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GestionReservationsEmprunts.setText("Gestion Reservations et Emprunts");
        GestionReservationsEmprunts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionReservationsEmpruntsActionPerformed(evt);
            }
        });
        getContentPane().add(GestionReservationsEmprunts);
        GestionReservationsEmprunts.setBounds(50, 200, 300, 68);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GestionUsagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionUsagerActionPerformed
        GestionUsager gu = new GestionUsager();
        this.dispose();
        gu.setVisible(true);
    }//GEN-LAST:event_GestionUsagerActionPerformed

    private void DeconnecterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeconnecterActionPerformed
        Authentification a = new Authentification();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_DeconnecterActionPerformed

    private void GestionOeuvresExamplairesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionOeuvresExamplairesActionPerformed
        GestionOeuvresExemplaires goe = new GestionOeuvresExemplaires();
        this.dispose();
        goe.setVisible(true);
    }//GEN-LAST:event_GestionOeuvresExamplairesActionPerformed

    private void GestionReservationsEmpruntsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionReservationsEmpruntsActionPerformed
        GestionReservationsEmprunts gre = new GestionReservationsEmprunts();
        this.dispose();
        gre.setVisible(true);
    }//GEN-LAST:event_GestionReservationsEmpruntsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Deconnecter;
    private javax.swing.JButton GestionOeuvresExamplaires;
    private javax.swing.JButton GestionReservationsEmprunts;
    private javax.swing.JButton GestionUsager;
    // End of variables declaration//GEN-END:variables
}
